### ISSUE TITLE
What do you use to manage your dotfiles?

### ISSUE THREAD

**Issue by mainrs** [igorvisi/dotfiles#1]
I am still looking for a way to manage dotfiles. I am not sure if such a tool exists but dedicated theme support would be cool (like including different files into xinitrc depending on the theme and stuff like that). Maybe even symlink multiple files depending on what theme someone selected.

**Comment by igorvisi** [comment]
I use [dotbot](https://github.com/anishathalye/dotbot) to manage my dotfiles. It just makes symlink. @SirWindfield, You can take a look at [wal](https://github.com/dylanaraps/wal) I don't know if that's what you're looking for.

**Comment by mainrs** [comment]
@igorvisi Thanks!

**Comment by igorvisi** [comment]
You are welcome @SirWindfield
